#! /usr/bin/env python

"""
Generate some internal code.
"""

from __future__ import absolute_import
from collections import defaultdict
from pykit.ir import ops

def gen_builder():
    """
    Generate code for pykit.ir.builder operations.
    """
    pos = defaultdict(int) # { 'opname': index }
    lines = list(open(ops.__file__))
    for name, op in vars(ops).iteritems():
        if isinstance(op, basestring) and name not in ('__file__', '__name__',
                                                       'constant'):
            for i, line in enumerate(lines):
                if op in line:
                    pos[op] = i
                    break

    order = sorted((lineno, op) for op, lineno in pos.iteritems())
    print("    # Generated by pykit.utils._generate")
    for lineno, op in order:
        if op[0].isupper():
            print("    %-20s = _const(ops.%s)" % (op, op))
        else:
            print("    %-20s = _op(ops.%s)" % (op, op))

if __name__ == "__main__":
    gen_builder()